### ISSUE TITLE
Marlin UPDATE ?

### ISSUE THREAD

**Issue by etet100** [mikeshub/Marlin2#1]
Hi. How old is Marlin you use?  Are you going to update it to the most recent version?

**Comment by michaelVisimid** [comment]
When I started it was. You are going to want to use the official Marlin 2.0 branch as the changes I've made here have already been incorporated into the main branch. I assume you are trying to get Marlin up an running on a Creator Pro? 

I have another pull request I am going to make to the main branch soon that makes the double nozzle work really well with Cura, but I released the magic smoke on my main board about a month ago and just now got the replacement back from China. Nothing too major coming in that change.

**Comment by mikeshub** [comment]
https://github.com/MarlinFirmware/Marlin/pull/12855

**Comment by etet100** [comment]
Hi. Thank you. I already have current version installed on my Creator for a few days. I will check new version today.

Good luck with your board!
